// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Travel.Api.Data;

#nullable disable

namespace Travel.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251111084540_AddPaymentAndRefundModels")]
    partial class AddPaymentAndRefundModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Travel.Api.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booking_date")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CancellationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("cancellation_status");

                    b.Property<bool>("Confirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("confirmed");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Guests")
                        .HasColumnType("integer")
                        .HasColumnName("guests");

                    b.Property<int>("Nights")
                        .HasColumnType("integer")
                        .HasColumnName("nights");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<bool>("ReminderSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("reminder_sent");

                    b.Property<string>("Review")
                        .HasColumnType("text")
                        .HasColumnName("review");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_price");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_bookings_user_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Travel.Api.Models.BookingDestination", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<int>("DestinationId")
                        .HasColumnType("integer")
                        .HasColumnName("destination_id");

                    b.HasKey("BookingId", "DestinationId");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("idx_bookingdest_dest_id");

                    b.ToTable("booking_destinations", (string)null);
                });

            modelBuilder.Entity("Travel.Api.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("destination_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DestinationId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("price");

                    b.HasKey("DestinationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("destinations", (string)null);

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            City = "Goa",
                            Country = "India",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 45, 39, 581, DateTimeKind.Utc).AddTicks(9210),
                            Description = "Golden beaches, vibrant shacks, and Portuguese heritage for a sun-soaked getaway.",
                            ImageUrl = "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1200&auto=format&fit=crop",
                            Latitude = 15.2993m,
                            Longitude = 74.1240m,
                            Name = "Goa Coastline Escape",
                            Price = 5200m
                        },
                        new
                        {
                            DestinationId = 2,
                            City = "Munnar",
                            Country = "India",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 45, 39, 581, DateTimeKind.Utc).AddTicks(9225),
                            Description = "Mist-covered mountains, endless tea gardens, and cool breezes in Kerala's hill country.",
                            ImageUrl = "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
                            Latitude = 10.0889m,
                            Longitude = 77.0595m,
                            Name = "Munnar Tea Highlands",
                            Price = 4000m
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "Jaipur",
                            Country = "India",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 45, 39, 581, DateTimeKind.Utc).AddTicks(9228),
                            Description = "The Pink City's palaces, royal bazaars, and forts wrapped in Rajasthan heritage.",
                            ImageUrl = "https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=1200&auto=format&fit=crop",
                            Latitude = 26.9124m,
                            Longitude = 75.7873m,
                            Name = "Jaipur Royal Circuit",
                            Price = 4800m
                        },
                        new
                        {
                            DestinationId = 4,
                            City = "Bali",
                            Country = "Indonesia",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 45, 39, 581, DateTimeKind.Utc).AddTicks(9230),
                            Description = "Balinese temples, terraced rice fields, and sunset beaches for an island escape.",
                            ImageUrl = "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1200&auto=format&fit=crop",
                            Latitude = -8.3405m,
                            Longitude = 115.0920m,
                            Name = "Bali Island Retreat",
                            Price = 18500m
                        },
                        new
                        {
                            DestinationId = 5,
                            City = "Paris",
                            Country = "France",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 45, 39, 581, DateTimeKind.Utc).AddTicks(9233),
                            Description = "Iconic boulevards, cafés, and museums in the heart of the City of Light.",
                            ImageUrl = "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1200&auto=format&fit=crop",
                            Latitude = 48.8566m,
                            Longitude = 2.3522m,
                            Name = "Paris City Lights",
                            Price = 45000m
                        },
                        new
                        {
                            DestinationId = 6,
                            City = "Santorini",
                            Country = "Greece",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 45, 39, 581, DateTimeKind.Utc).AddTicks(9264),
                            Description = "Blue-domed churches, whitewashed cliffs, and legendary caldera sunsets.",
                            ImageUrl = "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?q=80&w=1200&auto=format&fit=crop",
                            Latitude = 36.3932m,
                            Longitude = 25.4615m,
                            Name = "Santorini Sunset Escape",
                            Price = 52000m
                        },
                        new
                        {
                            DestinationId = 7,
                            City = "Tokyo",
                            Country = "Japan",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 45, 39, 581, DateTimeKind.Utc).AddTicks(9267),
                            Description = "Neon-lit streets, ancient temples, and cutting-edge technology in Japan's capital.",
                            ImageUrl = "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?q=80&w=1200&auto=format&fit=crop",
                            Latitude = 35.6762m,
                            Longitude = 139.6503m,
                            Name = "Tokyo Urban Explorer",
                            Price = 65000m
                        },
                        new
                        {
                            DestinationId = 8,
                            City = "Interlaken",
                            Country = "Switzerland",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 45, 39, 581, DateTimeKind.Utc).AddTicks(9270),
                            Description = "Snow-capped peaks, crystal-clear lakes, and charming alpine villages.",
                            ImageUrl = "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1200&auto=format&fit=crop",
                            Latitude = 46.8182m,
                            Longitude = 8.2275m,
                            Name = "Swiss Alps Adventure",
                            Price = 55000m
                        },
                        new
                        {
                            DestinationId = 9,
                            City = "Dubai",
                            Country = "UAE",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 45, 39, 581, DateTimeKind.Utc).AddTicks(9272),
                            Description = "Iconic skyscrapers, desert safaris, and world-class shopping in the UAE.",
                            ImageUrl = "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1200&auto=format&fit=crop",
                            Latitude = 25.2048m,
                            Longitude = 55.2708m,
                            Name = "Dubai Luxury Experience",
                            Price = 58000m
                        },
                        new
                        {
                            DestinationId = 10,
                            City = "Cusco",
                            Country = "Peru",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 45, 39, 581, DateTimeKind.Utc).AddTicks(9274),
                            Description = "Ancient Incan citadel, Andean mountains, and mystical cloud forests.",
                            ImageUrl = "https://images.unsplash.com/photo-1587595431973-160d0d94add1?q=80&w=1200&auto=format&fit=crop",
                            Latitude = -13.1631m,
                            Longitude = -72.5450m,
                            Name = "Machu Picchu Trek",
                            Price = 42000m
                        },
                        new
                        {
                            DestinationId = 11,
                            City = "Sydney",
                            Country = "Australia",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 45, 39, 581, DateTimeKind.Utc).AddTicks(9277),
                            Description = "Iconic Opera House, Harbour Bridge, and pristine beaches in Australia's harbor city.",
                            ImageUrl = "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1200&auto=format&fit=crop",
                            Latitude = -33.8688m,
                            Longitude = 151.2093m,
                            Name = "Sydney Harbour Escape",
                            Price = 48000m
                        },
                        new
                        {
                            DestinationId = 12,
                            City = "Reykjavik",
                            Country = "Iceland",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 45, 39, 581, DateTimeKind.Utc).AddTicks(9279),
                            Description = "Glaciers, geysers, waterfalls, and the magical aurora borealis.",
                            ImageUrl = "https://images.unsplash.com/photo-1539635278303-d4002c07eae3?q=80&w=1200&auto=format&fit=crop",
                            Latitude = 64.9631m,
                            Longitude = -19.0208m,
                            Name = "Iceland Northern Lights",
                            Price = 62000m
                        });
                });

            modelBuilder.Entity("Travel.Api.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("feedback_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeedbackId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.HasKey("FeedbackId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_feedbacks_created_at");

                    b.ToTable("feedbacks", (string)null);
                });

            modelBuilder.Entity("Travel.Api.Models.TravelPackage", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("package_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PackageId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("price");

                    b.HasKey("PackageId");

                    b.ToTable("travel_packages", (string)null);

                    b.HasData(
                        new
                        {
                            PackageId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Five-day coastal escape featuring sunrise yoga, local seafood tastings, and resort-style beach villas.",
                            ImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
                            Name = "Beach Escape",
                            Price = 499.99m
                        },
                        new
                        {
                            PackageId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Week-long alpine expedition with guided summit treks, riverside camping, and stargazing under clear skies.",
                            ImageUrl = "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
                            Name = "Mountain Adventure",
                            Price = 899.99m
                        },
                        new
                        {
                            PackageId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Curated heritage trail showcasing palace walkthroughs, artisan workshops, and immersive food tours.",
                            ImageUrl = "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=1200&q=80",
                            Name = "Cultural Journey",
                            Price = 699.99m
                        },
                        new
                        {
                            PackageId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modern city vibes with cutting-edge technology, vibrant nightlife, and cultural landmarks.",
                            ImageUrl = "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?q=80&w=1200&auto=format&fit=crop",
                            Name = "Urban Explorer",
                            Price = 799.99m
                        },
                        new
                        {
                            PackageId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium destinations featuring world-class accommodations, exclusive experiences, and personalized service.",
                            ImageUrl = "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1200&auto=format&fit=crop",
                            Name = "Luxury Worldwide",
                            Price = 1499.99m
                        },
                        new
                        {
                            PackageId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thrilling outdoor activities, breathtaking landscapes, and unforgettable natural wonders.",
                            ImageUrl = "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1200&auto=format&fit=crop",
                            Name = "Adventure Seeker",
                            Price = 1099.99m
                        },
                        new
                        {
                            PackageId = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rich history, architectural marvels, and culinary traditions across Europe's most iconic cities.",
                            ImageUrl = "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1200&auto=format&fit=crop",
                            Name = "European Heritage Tour",
                            Price = 1199.99m
                        });
                });

            modelBuilder.Entity("Travel.Api.Models.TravelPackageDestination", b =>
                {
                    b.Property<int>("TravelPackageId")
                        .HasColumnType("integer")
                        .HasColumnName("package_id");

                    b.Property<int>("DestinationId")
                        .HasColumnType("integer")
                        .HasColumnName("destination_id");

                    b.HasKey("TravelPackageId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("travel_package_destinations", (string)null);
                });

            modelBuilder.Entity("Travel.Api.Models.TripCancellation", b =>
                {
                    b.Property<int>("TripCancellationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("trip_cancellation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TripCancellationId"));

                    b.Property<string>("AdminComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("admin_comment");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("TripCancellationId");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("idx_tripcancellations_booking_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_tripcancellations_user_id");

                    b.ToTable("trip_cancellations", (string)null);
                });

            modelBuilder.Entity("Travel.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Picture")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Travel.Api.Models.Booking", b =>
                {
                    b.HasOne("Travel.Api.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Travel.Api.Models.BookingDestination", b =>
                {
                    b.HasOne("Travel.Api.Models.Booking", "Booking")
                        .WithMany("BookingDestinations")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Travel.Api.Models.Destination", "Destination")
                        .WithMany("BookingDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Travel.Api.Models.TravelPackageDestination", b =>
                {
                    b.HasOne("Travel.Api.Models.Destination", "Destination")
                        .WithMany("TravelPackageDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Travel.Api.Models.TravelPackage", "TravelPackage")
                        .WithMany("TravelPackageDestinations")
                        .HasForeignKey("TravelPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("TravelPackage");
                });

            modelBuilder.Entity("Travel.Api.Models.TripCancellation", b =>
                {
                    b.HasOne("Travel.Api.Models.Booking", "Booking")
                        .WithMany("TripCancellations")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Travel.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Travel.Api.Models.Booking", b =>
                {
                    b.Navigation("BookingDestinations");

                    b.Navigation("TripCancellations");
                });

            modelBuilder.Entity("Travel.Api.Models.Destination", b =>
                {
                    b.Navigation("BookingDestinations");

                    b.Navigation("TravelPackageDestinations");
                });

            modelBuilder.Entity("Travel.Api.Models.TravelPackage", b =>
                {
                    b.Navigation("TravelPackageDestinations");
                });

            modelBuilder.Entity("Travel.Api.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
